[project]
name = "pydantic-ai-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "asyncpg>=0.30.0",
    "logfire[asyncpg]>=3.16.0",
    "pydantic-ai>=0.2.6",
]
